-- Expand Trucks Table
ALTER TABLE trucks ADD COLUMN IF NOT EXISTS type_code VARCHAR(20) DEFAULT 'TR';
ALTER TABLE trucks ADD COLUMN IF NOT EXISTS type_description VARCHAR(100) DEFAULT 'Tractor (Semi)';
ALTER TABLE trucks ADD COLUMN IF NOT EXISTS dot_number VARCHAR(50);
ALTER TABLE trucks ADD COLUMN IF NOT EXISTS terminal VARCHAR(255) DEFAULT '1805 CHEMIN SAINT-FRANCOIS';
ALTER TABLE trucks ADD COLUMN IF NOT EXISTS insurance_policy VARCHAR(100);
ALTER TABLE trucks ADD COLUMN IF NOT EXISTS state_province VARCHAR(10) DEFAULT 'QC';

-- Expand Trailers Table
ALTER TABLE trailers ADD COLUMN IF NOT EXISTS type_code VARCHAR(20) DEFAULT 'TL';
ALTER TABLE trailers ADD COLUMN IF NOT EXISTS type_description VARCHAR(100) DEFAULT 'Semi truck trailer';
ALTER TABLE trailers ADD COLUMN IF NOT EXISTS terminal VARCHAR(255) DEFAULT '1805 CHEMIN SAINT-FRANCOIS';
ALTER TABLE trailers ADD COLUMN IF NOT EXISTS state_province VARCHAR(10) DEFAULT 'QC';

-- Expand Drivers Table
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS first_name VARCHAR(100);
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS middle_name VARCHAR(100);
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS last_name VARCHAR(100);
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS gender VARCHAR(10);
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS dob VARCHAR(50);
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS citizenship VARCHAR(100) DEFAULT 'Canada';
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS terminal VARCHAR(255) DEFAULT '1805 CHEMIN SAINT-FRANCOIS';
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS fast_id VARCHAR(100);
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS travel_doc_number VARCHAR(100);
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS travel_doc_type VARCHAR(50) DEFAULT 'Passport';
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS travel_doc_country VARCHAR(10) DEFAULT 'CA';
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS email VARCHAR(100);
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS phone VARCHAR(50);
